name: Find contributions
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  find-contributions:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install octokit
        run: npm install octokit
      - name: Get contributions
        run: |
          require('octokit')
          contributions = octokit.repos.getContributions('sujalgera01', {
            per_page: 100,
            since: '1 week ago'
          })
          console.log(contributions)
